a = input('digite algo: ')
print('o tipo primitivo desse valor é: ', type(a))
print('possui espaços?', a.isspace())
print('é númerico:', a.isnumeric())
print('está em letras maiúsculas?', a.isupper())
print('está em letras minúsculas?', a.islower())
